version: "3.3"
services:
  app: # 任意の名前
    container_name: php
    build: ./infra/php # ビルドコンテキスト(ビルドの場所)
    volumes:
      # - ./backend:/usr/share/nginx/html # ホスト側のディレクトリをコンテナ側にマウント
      - type: bind
        source: ./backend
        target: /usr/share/nginx/html
    depends_on:
      - db

  web: #任意の名前
    container_name: nginx
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./backend
        target: /usr/share/nginx/html
      - type: bind
        source: ./infra/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    container_name: mysql
    # build: ./infra/mysql
    image: mysql/mysql-server:8.0
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: ${TZ}
    volumes:
      - type: bind
        source: ./infra/mysql/data
        target: /var/lib/mysql
        # - db-store:/var/lib/mysql
      - type: bind
        source: ./infra/mysql/my.cnf
        target: /etc/my.cnf

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 3000:80
    environment:
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - type: bind
        source: ./infra/phpmyadmin/sessions
        target: /sessions
    depends_on:
      - db

# volumes:
#   db-store: